### ISSUE TITLE
MSBuild SDK attribute - programmatic detection during property evaluation

### ISSUE THREAD

**Issue by kygagner** [tillig/tillig.github.io#13]
Hi Travis,

I am the de-facto build engineer for a team of software developers who, for good reason I believe, have decided on an overwhelmingly complex deployment. Your blog has saved my skin a couple of times, so on the off chance that you might be able to answer my query, here it is: After three rewrites of my custom MSBuild scripts, I finally got a good extensible architecture, and now that we are beginning to use .NET Standard and .NET Core with the new clean project file format using the SDK attribute, I find myself supporting a legacy of both the old way and the new way since our solution is approaching 200 projects and we don't want to migrate all at once. Our build is driven through the normal solution build mechanism rather than being driven by my script, and each project has some boiler plate which imports my scripts, hooking themselves deep into the bowels of Microsoft's build. \<ContentWarning reason="blatant misuse of build">We name mangle assembly identities at build time during property evaluation because some components are deployed to customers without a strong guarantee of compatibility and we want to make their identities unique between releases.\</ContentWarning> We need to know whether we are building using the traditional imports or using the SDK attribute. Have you discovered a property set in the SDK props file import which I could use during the property evaluation phase of MSBuild to accomplish this?

Best Regards and many thanks for your blog,
Kyle

**Comment by tillig** [comment]
Wow, this sounds... _complex_. It took a couple read-throughs but I think I see what you're asking.

But... No. I haven't seen any way to easily indicate which project structure a given project is using. From what I've seen, they do their best to make that transparent from the consumer perspective, sort of how you don't really know at build time if a project uses `packages.config` or `<PackageReference>`. You might be able to dive into the project system itself and, say, write a custom build tall that interrogates a specified project to get the data... But at that point you could always just XmlPeek at the project file, too.

And maybe that's the simplest thing that could possibly work - XmlPeek to see what it is.

Sorry I'm not more help. I've actually been spending a lot more time in PowerShell and PowerShell Core for my builds lately because I'm doing a lot more in .NET Core where I have to call the dotnet CLI a lot.

**Comment by kygagner** [comment]
Hi,

Thanks for your prompt response. Unfortunately, XmlPeek is out because once property evaluation has finished, the damage is done. Too many things have been computed from the assembly identity to fix at that point, nor would it be reasonable to try as a new one could be added by Microsoft at any point, becoming a game of whack-a-mole and major point of weakness. I may just mandate as part of my boilerplate that the project file sets a property :( I will comment again if I find a better solution.

Kyle

**Comment by tillig** [comment]
It may be something to consider that... maybe it doesn't matter. I get that you may have some requirements to figure this out and so on, so I don't want to argue that. I just know that when I see stuff like this in my day-to-day I like to step back and ask why trying to circumvent the layers of abstraction (or whatever) is valuable. What am I trying to accomplish? Is it troubleshooting the build system? Could I accomplish it with a different mechanism (like a report generated post-build or something added as a tag to a NuGet package)? Again, I don't really have a horse in the race, but if it turns out you have to do a lot of work to get this to happen, maybe... maybe there's a different solution to the problem.

**Comment by kygagner** [comment]
On that train of thought, I am considering cutting out name mangling support for the legacy project style - which would solve the problem. The rework is limited in scope because we don't need to deploy many assemblies like that. I might have to placate a grumpy engineer or two, but you're absolutely right. Maybe I'll roll it out with a performance enhancement as a diversion tactic ;P
