### ISSUE TITLE
Sphero battery?

### ISSUE THREAD

**Issue by zevv** [tillig/tillig.github.io#24]
Hi there,

I just found your blog where you mentioned that the super nice people at sphero replaced your robot for free when the battery gave up. Unfortunately, I have the same issue, but I am offered no solution - it can not be repaired, I have to throw it away and Sphero can not help me. This makes both me and my 10 y.o. pretty sad, it is such a wast since the rest of the robot is still perfectly fine!

Was there anything special in your communication with Sphero that made them offer you a replacement?

Thanks a lot!

Ico

**Comment by tillig** [comment]
No, I didn't say anything special that I'm aware of. I just explained the situation, how I had a dead Sphero and was curious if there was a way to replace the battery or otherwise get it repaired. They did ask for a photo of the dead Sphero's serial number, which I provided, and then they just offered a replacement. Perhaps I got lucky, or perhaps I had a Sphero that was part of a known bad production run? I went in fully expecting to have to purchase a new one, though, and didn't ever specifically _ask_ for a free replacement. Perhaps because I didn't ask and didn't expect anything I was just given a nice surprise.

As you noticed, I did try to replace the battery myself with little luck. I'm not sure if it was something I did or just because the electronics couldn't handle it. You could always try that, perhaps you'd have better luck than I did.

**Comment by zevv** [comment]
Well, they might have changed their policy recently maybe - I just sent a support message because I was no longer able to wake the robot up once it was off the charger, and their conclusion was that it is now e-waste. I must admit I was kind of disappointed, given the overall quality (and price!) of the robot.

I found your post looking for other peoples experiences with battery replacement - I guess it's probably not worth cracking it open then.

Thanks !
