### ISSUE TITLE
Question in regards of your Deep Dive into Microsoft Configuration blog

### ISSUE THREAD

**Issue by shirlik** [tillig/tillig.github.io#26]
First I want to say thanks for your great explanation.

I have a case in which new projects , developed in .NET standard (originally they developed in .NET framework), 
are going to be used by .NET framework and .NET core applications .

These new projects are using configuration.

The .NET framework app working with app.config and web.config and we can't change it.
The .NET core works with appsettings.json and we can't add app.config .

What is the best approach for using configuration in the .NET standard projects ?
create custom configuration provider in Microsoft extensions and  try transform the existing XML config into new XML config .
or create new abstraction of IMyConfiguration and add implementation for each platform.

I will appreciate any advise,
thanks

**Comment by tillig** [comment]
This isn't really about my deep dive since I didn't address web.config at all. 😄 The fact is, there's no bridge between the two. My advice would be to change the app that uses web.config to use new `IConfiguration`. [This Microsoft doc effectively gives the same advice.](https://docs.microsoft.com/en-us/dotnet/architecture/blazor-for-web-forms-developers/config) If you can't change either app... There's nothing to be done. Sorry.

**Comment by shirlik** [comment]
Can I change the .NET framework apps to work with IConfiguration and still keep the configuration in app.config and web.config files? In these files I have configSections that I want to use with IConfiguration in our .NET standard modules .

**Comment by tillig** [comment]
There's nothing to do that out of the box, so if you do, it's all custom code. So... can you? That's a question for you and your coding abilities.
