### ISSUE TITLE
Consultation on memory leak

### ISSUE THREAD

**Issue by cpkuo** [tillig/tillig.github.io#27]
Hi, excuse me if this isn't the proper channel to reach out. I clicked the "Contact" link on your blog. In any case,  you recently responded to me regarding a memory leak issue in the Multitenant package. I've updated my code so that all tenants are registered accordingly yet I still see rising memory usage and appears the Multitenant container isn't releasing objects. I was wondering if I could book an hour of your time (paid) to help me look over what I am doing wrong. That would be greatly appreciated.

**Comment by tillig** [comment]
I think your best bet is [StackOverflow](https://stackoverflow.com) and tag your question `autofac`. Unfortunately, I don't have the bandwidth at the moment for consulting and I know I (and the other Autofac owners, and the community) also monitor there to help folks out.

Part of asking on SO (and the first thing I'd do if consulting) is too make a super minimal reproduction. Take as much out of the equation as possible to see what's absolutely the minimum in order to see the issue. A lot of the time what I see is the app is really complex and different teams or devs are doing different things and, as the app has grown organically, something got set up wrong or something is happening that no one realized was happening. Forcing yourself to get that minimal repro find those things.

If it's still an issue, that repro can help answerers focus on the important bits.

Again, sorry I can't dive in directly. If I see the SO question, I'll try to answer if I can.
