### ISSUE TITLE
Laser beard removal

### ISSUE THREAD

**Issue by rskalenyc** [tillig/tillig.github.io#7]
Hi Travis,

Firstly, just wanted to thank you for sharing your laser beard removal/reduction journey on your blog along with all the tips. I'm considering having this done myself in NYC and there's not many successful before/after examples online with much detail about how the procedures went. There's also some scary stories. Your hair/skin combo is somewhat the same as mine and I can only hope to have a similar outcome.

I read through each of your treatment blog post updates and have some questions:

-What ultimately made you choose the facility you went with? Was it a referral? Were you looking for the best specialist in your area? (I assume you had this done in Oregon?)

-I hear a lot about the YAG and Alexandrite lasers for beard removal. Had you come across or done any research on these at any point? When googling the topic, there is an episode of 'The Doctors' where they use a Lumenis Light Sheer laser. The pain is supposedly a lot more tolerable. Have you heard anything on this? There doesn't seem to be much info.

-Lastly, how much did the total procedure cost?

Many thanks,
Chris

**Comment by tillig** [comment]
Hey.

Given it's been over six years since my last treatment, I don't have a whole lot of very specific details at my fingertips. For example, I couldn't tell you exactly which laser at which setting they used. I remember it was a MeDioStar laser that, if I recall correctly, looked [very much like this one](http://www.ebay.com/itm/like/141953378399?lpid=82&chn=ps&ul_noapp=true) but no guarantees that was it.

To be honest, I didn't do super extensive research about all the possible lasers and hair removal mechanisms it sounds like you've done. A lot has changed in the nine years since I started my first treatment. (If you do the math there, you'll notice I was going for _three years_ to get where I did.)

I did look at the different places in Oregon around my area that offered the services I was looking for. I was honestly less concerned with price than I was with service, so the things I looked at were more from people claiming positive or negative experiences and success stories than trying to find the cheapest place. I do recall most of the places I priced were roughly the same at the time.

Given it's been nine years since I started I'm guessing technology has been updated. ("The Doctors" didn't even start airing until a year after I started my procedure.) There may be less painful solutions. I hope there are. I don't need to go back - my results still look the same as they did six years ago when I finished - but I still remember how much it hurt and sometimes raise it as a sort of "badge of honor" when people are bragging about tattoos or piercings and their pain threshold.

I don't remember how much it cost. It was not cheap. I'm _vaguely_ recalling around $100/session. Don't quote me on that. It may have been more. I'm sure with inflation and medical costs today it's probably going to at least be that much. The price changed a bit over the course of the three years I was going, I do remember that. But sorry I can't be more specific.

I will close with this: I'm still totally glad I did it. I was shredding the necks on my shirts. I was destroying pillowcases. My five-o-clock shadow was thick enough I could kiss my wife on the cheek and leave a red mark. It wasn't good. I still have to shave, but none of those other problems plague me. Worth it.

**Comment by rskalenyc** [comment]
Wow, that's great to hear your results still look the same after six years. Sounds like it was a good investment for you.

Honestly, my situation isn't as dire as yours sounded. I should be shaving every day but it's irritating on the skin the skin so I have to limit it to M/W/F and then let my skin "breathe" on weekends. Even when I'm freshly shaved you can still see a slight shadow. I'm hoping to achieve a more naturally smooth look when clean shaven similar to yours.

Do you at least find it easier to shave daily now than before? Is the actual process itself smoother and less irritating?

I've given myself quite some time to really think about it. It's a big step and I'm mostly nervous about most of the common burn and patchy stories around but I think I'm about ready to take the plunge. The "scruffy" look doesn't do anything for me and I'm growing tired of every other day having to be a "crappy looking day". I was hoping to have significantly less hair overall and have to shave less often. However, if I have to now make it a daily routine in order to conceal some obvious signs of patching that may show through, then that's something I'm still a bit apprehensive about.

Thank you again for all the info.

Chris
